-- Repair recruiter-facing case study sections for existing project data.
--
-- Usage from repository root:
--   /opt/homebrew/opt/postgresql@16/bin/psql -h localhost -U "$(whoami)" -d personal_brand_dev -f scripts/sql/update-project-case-study-sections.sql
--
-- This is a bulk repair script for already-input projects. Normal create/edit
-- should still happen through the admin workflow.

UPDATE projects
SET
  solution = E'Membangun Phoenix LiveView app sebagai portfolio CMS: PostgreSQL menyimpan content, Ecto changeset menjaga validasi, Backpex menyediakan admin CRUD, dan public LiveView merender homepage, work list, serta detail case study dari data yang sama.\n\nFokus implementasinya bukan hanya membuat halaman publik, tapi membuat workflow yang bisa dipakai harian: auto slug untuk URL stabil, taxonomy project untuk filtering recruiter, media library untuk cover/demo, site settings untuk About/Now/Contact, serta reset script agar data development bisa dipulihkan.',
  architecture_notes = E'Struktur utama sengaja dibuat sebagai Phoenix monolith dengan Content context sebagai boundary antara database, admin, dan public UI.\n1. Content context menjadi satu pintu query untuk published/draft record, slug lookup, featured project, taxonomy filtering, dan media attachment.\n2. Ecto schema dan changeset dipakai sebagai kontrak data agar admin Backpex dan public rendering membaca aturan validasi yang sama.\n3. Backpex resource dipisah per content type supaya Project, Post, Product, Media, SiteSetting, Theme, dan Tag tetap mudah dirawat.\n4. Public LiveView hanya membaca data yang sudah published, sehingga admin workflow dan recruiter-facing page tidak bercampur.',
  tradeoffs = E'Trade-off utama project ini adalah memilih scope yang cukup kuat untuk job search, tapi tetap ringan untuk dibangun dan dirawat sendiri.\n1. Taxonomy memakai array field dulu, bukan taxonomy table penuh. Ini mempercepat filtering platform/discipline, dengan konsekuensi query dan reporting belum sefleksibel relational model.\n2. Backpex dipakai untuk ship admin CMS cepat. Konsekuensinya beberapa UI perlu custom renderer agar terasa rapi, tapi CRUD dasar tidak perlu dibangun dari nol.\n3. Media storage masih local/external URL. Ini cukup untuk development dan portfolio pribadi, tapi production jangka panjang perlu object storage seperti S3-compatible storage.\n4. Site settings dibuat singleton agar data About/Now/Contact konsisten, dengan konsekuensi admin tidak butuh create/delete record untuk setting.',
  sort_date = DATE '2026-05-01',
  updated_at = NOW()
WHERE slug = 'personal-platform-website';

UPDATE projects
SET
  solution = E'Postie dibangun sebagai aplikasi macOS native untuk menghindari overhead Electron pada API client modern. SwiftUI menangani interface utama, AppKit dipakai untuk area yang butuh kontrol lebih rendah seperti text rendering dan file panel, sementara URLSession menjadi layer networking.\n\nPendekatannya dibuat simple tapi ketat: MVVM memisahkan state UI dari logic request, service layer menangani networking/collection/environment, async-await dipakai untuk flow request modern, dan cache dibersihkan secara eksplisit setelah response agar memory footprint tetap rendah.',
  architecture_notes = E'Arsitektur Postie memakai MVVM + Service Layer agar UI, state, dan IO tidak saling bercampur.\n1. ViewModel menyimpan UI state dan mengorkestrasi event dari user seperti send request, switch environment, dan render response.\n2. NetworkService, FileService, CollectionService, dan EnvironmentService dibuat stateless supaya business logic mudah dites dan predictable.\n3. URLSession menjadi boundary networking, sehingga request/response handling tidak bergantung ke third-party HTTP client.\n4. NSTextView dipakai untuk payload besar agar rendering JSON/HTML lebih stabil dibanding memaksa semuanya ke SwiftUI Text.\n5. NSSavePanel dan NSOpenPanel menjaga operasi file tetap sesuai sandboxing macOS.',
  tradeoffs = E'Postie sengaja memilih native-first dan privacy-first, walaupun itu membuat scope development lebih berat.\n1. Tidak memakai Electron. Alternatif itu bisa mempercepat cross-platform delivery, tapi native macOS memberi startup, memory usage, dan feel UI yang lebih baik untuk target user.\n2. Tidak memakai third-party dependencies. Konsekuensinya lebih banyak komponen dibangun sendiri, tapi supply-chain risk dan dependency maintenance menjadi jauh lebih kecil.\n3. Tidak menambahkan cloud sync dan telemetry. User privacy lebih kuat, tetapi insight usage dan sinkronisasi antar device harus ditunda.\n4. UserDefaults cukup untuk storage awal karena scope data masih sederhana. Jika collection semakin kompleks, storage perlu naik ke SQLite/Core Data.',
  sort_date = DATE '2025-12-01',
  updated_at = NOW()
WHERE slug = 'postie-native-macos-api-client';

UPDATE projects
SET
  solution = E'Membangun backend portfolio sebagai Phoenix monolith dengan PostgreSQL untuk persistence, Ecto untuk schema/changeset, Content context untuk read/write boundary, dan Backpex untuk admin CRUD. Layer ini mengelola published/draft workflow, slug generation, taxonomy filtering, media attachment, dan site settings.\n\nPendekatan teknisnya diarahkan ke recruiter-facing output: data project tidak cuma tersimpan, tapi bisa dirender menjadi detail work yang menjelaskan role, ownership, stack, decision, result, dan evidence tanpa edit HTML manual.',
  architecture_notes = E'Backend dibuat dengan boundary yang jelas antara schema, context, admin resource, dan public rendering.\n1. Project, Post, Product, Media, Tag, Theme, dan SiteSetting menjadi content type utama dengan Ecto schema dan changeset masing-masing.\n2. Content context menjadi query boundary untuk published/draft filter, slug lookup, featured sorting, dan taxonomy filtering.\n3. Backpex LiveResource menangani admin CRUD, sementara custom renderer/form helper dipakai untuk field taxonomy, structured textarea, media, dan preview actions.\n4. Public LiveView membaca data lewat Content context, bukan query tersebar di template.\n5. Media attachment dan theme/site settings dipisah dari project agar presentation state tidak bercampur dengan case study data.',
  tradeoffs = E'Beberapa keputusan dibuat pragmatis karena goal utamanya adalah portfolio CMS yang cepat dipakai untuk job search.\n1. Enum array dipakai untuk platforms dan disciplines. Ini cepat untuk filter awal, tapi jika taxonomy makin kompleks perlu join table dan admin taxonomy management yang lebih kaya.\n2. Session-based admin auth cukup untuk single-owner local/admin usage. Untuk multi-admin production, perlu RBAC, audit log, dan hardening credential.\n3. Local media storage dan external URL dipakai dulu. Ini memudahkan development, tapi production perlu object storage dan lifecycle policy.\n4. Backpex mempercepat CRUD, tetapi desain admin perlu custom polish agar form panjang tetap nyaman dipakai.',
  sort_date = DATE '2026-05-01',
  updated_at = NOW()
WHERE slug = 'backend-architecture-personal-brand-platform-cms';

UPDATE projects
SET
  solution = E'Internak dibangun sebagai Flutter mobile app untuk membantu peternak mencatat data ternak, kandang, pakan, aktivitas harian, dan interaksi dengan pendamping. Implementasi memakai BLoC agar flow input bertahap tetap bisa dipisahkan antara UI, event, state, dan business logic.\n\nAplikasi juga menggabungkan integrasi yang penting untuk domain peternakan: maps/location untuk profil peternakan, REST API untuk sinkronisasi data, SSO untuk login multi-role, dan multi-flavor build agar dev/staging/production bisa dipisahkan tanpa mengubah kode fitur.',
  architecture_notes = E'Struktur aplikasi mengikuti feature-based Flutter architecture dengan BLoC sebagai state management utama.\n1. Setiap fitur dipisah ke layer view, bloc/event/state, model, dan repository agar perubahan UI tidak langsung merusak data flow.\n2. Repository menjadi boundary ke REST API, sehingga screen tidak memanggil endpoint secara langsung.\n3. Get It dipakai untuk dependency injection supaya service/repository bisa dipakai lintas fitur tanpa tight coupling.\n4. Go Router mengatur navigasi antar role dan flow onboarding/input data.\n5. Multi-flavor configuration memisahkan environment dev, staging, dan production untuk build Android.',
  tradeoffs = E'Keputusan teknis Internak dibuat untuk menjaga flow mobile yang kompleks tetap mudah ditelusuri.\n1. BLoC dipilih dibanding state management yang lebih ringan karena event-state trace lebih jelas untuk form bertahap dan multi-role flow.\n2. REST API dipakai karena backend sudah menyediakan endpoint terstruktur dan lebih familiar untuk tim, walaupun GraphQL bisa lebih fleksibel untuk query komposit.\n3. SSO mempercepat login user, tapi cache harus ditangani hati-hati saat berganti role atau akun.\n4. Multi-flavor build membantu QA antar environment, dengan konsekuensi konfigurasi build Android menjadi lebih kompleks.\n5. Banyak library UI dipakai untuk mempercepat delivery, tetapi daftar dependency perlu dijaga agar tidak membengkak tanpa kebutuhan nyata.',
  sort_date = DATE '2024-01-01',
  updated_at = NOW()
WHERE slug = 'internak-app-platform-monitoring-peternakan';
