-- Upsert recruiter-ready portfolio copy for Personal Platform Website.
--
-- Usage from repository root:
--   /opt/homebrew/opt/postgresql@16/bin/psql -h localhost -U "$(whoami)" -d personal_brand_dev -f scripts/sql/upsert-personal-platform-project.sql
--
-- This is intentionally a manual SQL fallback for dev data repair after reset.

INSERT INTO projects (
  id,
  title,
  slug,
  summary,
  description,
  problem,
  solution,
  result,
  role,
  tech_stack,
  year,
  status,
  featured,
  project_type,
  platforms,
  disciplines,
  ownership,
  team_size,
  duration,
  impact_summary,
  technical_highlights,
  architecture_notes,
  tradeoffs,
  metrics,
  demo_url,
  demo_video_url,
  github_url,
  case_study_visibility,
  sort_order,
  inserted_at,
  updated_at
) VALUES (
  '11111111-2222-4333-8444-555555555555',
  'Personal Platform Website',
  'personal-platform-website',
  'Platform personal berbasis Phoenix LiveView untuk menampilkan portfolio, writing, product, dan admin CMS dari satu sumber data.',
  'Personal Platform Website adalah aplikasi web full-stack yang dibangun sebagai single source of truth untuk portfolio kerja, tulisan, produk digital, media, theme, dan site settings. Project ini dirancang agar recruiter bisa membaca case study technical dengan cepat, sementara admin tetap bisa memperbarui konten tanpa menyentuh database langsung.',
  'Portfolio statis sulit dijaga ketika kebutuhan berubah: recruiter butuh bukti role, ownership, impact, dan technical depth; sementara pemilik portfolio butuh cara cepat menambah project, mengedit copy, mengelola media, dan menjaga URL publik tetap stabil. Tanpa CMS, data mudah tersebar dan update kecil bisa berubah jadi pekerjaan engineering manual.',
  'Membangun Phoenix LiveView app dengan PostgreSQL, Ecto schema/changeset, Backpex admin CMS, taxonomy project, auto slug, media library, site settings, theme registry, dan public route /work serta /work/:slug. Admin form dipoles dengan placeholder, suggestion, checkbox taxonomy, preview link, row actions, validation, dan reset workflow agar data portfolio bisa diulang dari baseline bersih.',
  ARRAY[
    'Public /work dan /work/:slug menampilkan project portfolio dengan format recruiter-focused.',
    'Admin CMS bisa create, edit, preview, dan delete project, post, product, media, site setting, dan theme.',
    'Database reset workflow bisa mengulang baseline development data secara bersih.',
    'Automated test suite menjaga perubahan schema, changeset, admin LiveView, dan public route tetap aman.'
  ],
  'Full-stack Software Engineer',
  ARRAY[
    'Elixir',
    'Phoenix LiveView',
    'PostgreSQL',
    'Ecto',
    'Backpex',
    'Tailwind CSS',
    'daisyUI',
    'Bash',
    'SQL'
  ],
  '2026',
  'published',
  TRUE,
  'personal_project',
  ARRAY['web', 'backend'],
  ARRAY['fullstack_engineering', 'backend_engineering', 'frontend_engineering', 'architecture'],
  'Solo builder end-to-end: product direction, schema design, admin CMS, public UI, tests, seed data, reset workflow, dan dokumentasi.',
  'Solo project with AI-assisted implementation review',
  '2026',
  'Menunjukkan kemampuan membangun platform web full-stack yang langsung mendukung kebutuhan job search: data portfolio terstruktur, case study publik, dan admin workflow yang bisa dipakai harian.',
  ARRAY[
    'Phoenix LiveView public pages untuk homepage, work list, dan project detail.',
    'Backpex resources untuk CRUD Projects, Posts, Products, Media, Site Settings, dan Themes.',
    'Ecto changeset validation untuk slug, taxonomy, URL, JSON config, dan structured textarea.',
    'Auto slug dan duplicate handling untuk menjaga URL /work/:slug tetap stabil.',
    'Reset database script dan SQL upsert manual untuk baseline development yang reproducible.',
    'Test coverage untuk content context, admin resources, auth, dan public rendering.'
  ],
  'Boundary utama berada di Content context dan Ecto schema. Public LiveView membaca data published berdasarkan slug/filter, sementara Backpex resource mengelola admin CRUD melalui changeset yang sama. Media, site settings, dan themes dipisahkan sebagai resource sendiri agar content data tidak tercampur dengan presentation state.',
  'Taxonomy project memakai array field terlebih dulu agar cepat dipakai untuk job search dan filtering. Ini trade-off yang lebih praktis untuk MVP dibanding langsung membuat taxonomy table penuh. Backpex dipakai untuk mempercepat CMS, lalu UX admin dipoles bertahap dengan custom renderer dan form controls.',
  ARRAY[
    '208 automated tests passing across content, admin, auth, and public rendering.',
    'Core public portfolio routes: /work and /work/personal-platform-website.',
    'Admin coverage: project CRUD plus posts, products, media, settings, and themes.',
    'Local workflow supports reset, migration, media upload, external media URLs, and recruiter-focused project editing.'
  ],
  NULL,
  NULL,
  'https://github.com/nunutech40/personal-platform-website',
  'public',
  0,
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  problem = EXCLUDED.problem,
  solution = EXCLUDED.solution,
  result = EXCLUDED.result,
  role = EXCLUDED.role,
  tech_stack = EXCLUDED.tech_stack,
  year = EXCLUDED.year,
  status = EXCLUDED.status,
  featured = EXCLUDED.featured,
  project_type = EXCLUDED.project_type,
  platforms = EXCLUDED.platforms,
  disciplines = EXCLUDED.disciplines,
  ownership = EXCLUDED.ownership,
  team_size = EXCLUDED.team_size,
  duration = EXCLUDED.duration,
  impact_summary = EXCLUDED.impact_summary,
  technical_highlights = EXCLUDED.technical_highlights,
  architecture_notes = EXCLUDED.architecture_notes,
  tradeoffs = EXCLUDED.tradeoffs,
  metrics = EXCLUDED.metrics,
  demo_url = EXCLUDED.demo_url,
  demo_video_url = EXCLUDED.demo_video_url,
  github_url = EXCLUDED.github_url,
  case_study_visibility = EXCLUDED.case_study_visibility,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();
