-- Upsert recruiter-ready portfolio copy for SAINS multi-product platform.
--
-- SAINS adalah monorepo dengan 1 backend Go (shared) yang mem-serve 4 frontend produk web:
--   - api            → https://github.com/nunutech40/subscription_app
--   - atomic         → https://github.com/nunutech40/atomic
--   - klinik         → https://github.com/nunutech40/invoice-generator-klinik
--   - kontrak        → https://github.com/nunutech40/kontrakpro
--   - surat          → https://github.com/nunutech40/template-surat
--
-- Usage from repository root:
--   /opt/homebrew/opt/postgresql@16/bin/psql -h localhost -U "$(whoami)" -d personal_brand_dev -f scripts/sql/upsert-sains-projects.sql
--
-- Skrip ini adalah manual SQL fallback yang bisa dipanggil ulang untuk refresh konten
-- tanpa harus nge-klik admin browser. Semua statement pakai ON CONFLICT (slug) DO UPDATE
-- sehingga aman diulang.

-- =====================================================================================
-- 1) SAINS API — Shared Go Backend (auth, subscription, payment, admin dashboard)
-- =====================================================================================
INSERT INTO projects (
  id,
  title,
  slug,
  summary,
  description,
  problem,
  solution,
  result,
  role,
  tech_stack,
  year,
  status,
  featured,
  project_type,
  platforms,
  disciplines,
  ownership,
  team_size,
  duration,
  impact_summary,
  technical_highlights,
  architecture_notes,
  tradeoffs,
  metrics,
  demo_url,
  demo_video_url,
  github_url,
  case_study_visibility,
  sort_order,
  sort_date,
  inserted_at,
  updated_at
) VALUES (
  'a1111111-2222-4333-8444-555500000001',
  'SAINS API — Shared Backend untuk Platform Multi-Produk',
  'sains-api-backend-shared-multi-produk',
  $$Go backend yang men-serve satu stack auth, subscription, pembayaran, dan admin dashboard untuk 4 produk web (Atomic, Klinik, KontrakPro, Surat) dalam satu monorepo SAINS.$$,
  $$SAINS API adalah binary Go tunggal yang dirancang sebagai single source of truth untuk autentikasi, subscription, pembayaran Midtrans, dan operasi admin dari beberapa produk web konsumen di bawah payung SAINS. Backend ini di-deploy satu kali di VPS IDCloudHost dan di-hit oleh empat frontend web berbeda lewat query param product, sehingga setiap produk baru tidak perlu stack backend tersendiri dan tim produk bisa fokus pada experience per segmen.$$,
  $$Beberapa produk SAINS butuh auth, paywall, dan dashboard admin dengan logika yang mirip, tetapi membangun backend terpisah per produk akan menghasilkan duplikasi kode, inkonsistensi kontrak API, dan biaya maintenance yang terus membesar. Selain itu platform ini butuh kontrol anti account-sharing dan akses guest yang viral-friendly tapi tetap bisa dipantau, sehingga model auth sederhana tidak cukup.$$,
  $$Membangun satu binary Go 1.23 dengan Gin, pgx v5, dan sqlc untuk query type-safe, plus golang-migrate untuk schema evolution. Auth pakai JWT access token 1 jam dan refresh token httpOnly 30 hari, dengan single-session rule yang otomatis revoke session lama setiap login baru. Pembayaran memakai Midtrans Snap dengan webhook idempotent yang meng-aktifkan subscription setelah settlement.

Admin dashboard di-render server-side pakai go:embed HTML template, HTMX, dan Tabler CSS, jadi tidak butuh SPA terpisah dan deploy tetap satu binary. Semua handler mengikuti lapisan handler → service → repository (sqlc-generated) → PostgreSQL, dengan struktur admin dipecah modular per domain (auth, audience, user, guest_code, subscription, pricing, revenue, anomaly, product, audit) supaya perubahan di satu fitur tidak menyentuh fitur lain.$$,
  ARRAY[
    'Satu binary Go men-serve 4 produk frontend (Atomic, Klinik, KontrakPro, Surat) lewat query parameter product tanpa perubahan skema per produk.',
    'Admin dashboard live di https://sains-atomic.web.id/admin dengan 12+ halaman (Dashboard, Audience, Users, Guest Codes, Subscriptions, Pricing, Revenue, Products, Settings, Audit Logs, Feedback, Anomalies).',
    'Midtrans Snap terintegrasi di produksi dengan webhook idempotent yang meng-aktifkan subscription setelah settlement.',
    'Anti account-sharing jalan: single-session rule + anomaly scoring (multi-session, IP/device switch, rapid login) + lock + revoke semua session dari satu tombol admin.',
    'Guest login 2-step (email + kode, lalu OTP 6 digit) dengan rate limit 3 OTP per 10 menit dan maksimum 2 login per email per kode aktif.'
  ],
  'Solo backend engineer / full-stack platform owner',
  ARRAY[
    'Go 1.23',
    'Gin',
    'pgx v5',
    'sqlc',
    'golang-migrate',
    'golang-jwt v5',
    'bcrypt',
    'HTMX',
    'Tabler CSS',
    'Chart.js',
    'PostgreSQL 16',
    'Midtrans Snap',
    'DomainNesia SMTP',
    'Nginx',
    'Cloudflare',
    'IDCloudHost VPS (Ubuntu)'
  ],
  '2026',
  'published',
  TRUE,
  'personal_project',
  ARRAY['backend', 'web'],
  ARRAY['backend_developer'],
  'Solo builder untuk desain skema, handler, service, SQL, admin dashboard, integrasi Midtrans + SMTP, setup VPS + Cloudflare, serta dokumentasi PRD/TRD/Architecture.',
  'Solo project',
  '2026',
  $$Menunjukkan kemampuan merancang backend satu-binari yang efisien untuk platform multi-produk: auth dengan model ancaman yang realistis, payment gateway dengan webhook idempotent, dan admin panel yang cukup matang untuk operasi harian, semuanya tanpa stack tambahan di luar Go + PostgreSQL + HTMX.$$,
  ARRAY[
    'Anomaly scoring system dengan multi-session, IP switch, device switch, dan rapid login; user di atas threshold otomatis flagged ke /admin/anomalies dan bisa di-lock + revoke semua session sekaligus.',
    'Single-session rule: login baru otomatis revoke session lama dan tulis anomaly log, mencegah account-sharing by design.',
    'Guest login 2-step dengan email + kode undangan → OTP 6 digit (expire 5 menit), plus maksimum 2 login per email per kode agar tetap kontrolable.',
    'Contract error yang konsisten: semua /api/* return { data | error: { code, message } } dengan kode terstandar (VALIDATION_ERROR, TOKEN_EXPIRED, QUOTA_FULL) untuk memudahkan frontend mapping.',
    'Admin panel modular per domain (admin_auth_handler.go, user_handler.go, pricing_handler.go, revenue_handler.go) dengan satu template per halaman, menekan blast radius perubahan.',
    'Webhook Midtrans idempotent di /api/midtrans/webhook dengan pengecekan signature dan state machine subscription yang aman di-replay.'
  ],
  $$Backend dipecah menjadi dua permukaan route dalam satu proses: /api/* return JSON untuk semua frontend produk, /admin/* return HTML untuk dashboard berbasis HTMX. Setiap handler mengikuti lapisan handler → service → repository (sqlc-generated) → PostgreSQL, dengan model domain terpisah dari generated code agar logic tidak bocor ke lapisan SQL.

Multi-product by design: frontend mengirim ?product=atomic|klinik|kontrak|surat dan backend memetakan ke plan, quota, serta access-check yang sesuai tanpa kode khusus per produk. Admin panel dipecah modular per domain sehingga refactor di satu halaman tidak menyentuh halaman lain, dan shared components (layout.html, helpers.go seperti formatIDR, uuidStr, parseUUID) didokumentasikan eksplisit dengan peta siapa memakainya.$$,
  $$Memilih HTMX + server-rendered HTML untuk admin ketimbang SPA React/Vue untuk menjaga deploy tetap satu binary dan tidak perlu build pipeline tambahan; konsekuensinya admin UI terikat server dan kurang rich-interaction. Query database pakai sqlc tanpa ORM untuk kontrol SQL penuh dan nol reflection, trade-off-nya perlu regenerate Go code setiap ubah file .sql. Halaman Audience sementara memuat 500 row lalu filter di Go; diakui sebagai utang teknis yang akan dipindah ke SQL WHERE ketika data tumbuh.$$,
  ARRAY[
    'Live di https://sains-atomic.web.id men-serve 4 produk frontend produksi.',
    'Target performance terdokumentasi: API p95 < 200ms sebagai non-functional requirement.',
    '~20 endpoint API (public + protected + admin) dan 12+ halaman admin terdokumentasi di URLS.md.',
    'Quota default 200 subscriber aktif + 50 guest (configurable) dipakai untuk progress bar dashboard.'
  ],
  'https://sains-atomic.web.id/admin/login',
  NULL,
  'https://github.com/nunutech40/subscription_app',
  'public',
  1,
  DATE '2026-02-27',
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  problem = EXCLUDED.problem,
  solution = EXCLUDED.solution,
  result = EXCLUDED.result,
  role = EXCLUDED.role,
  tech_stack = EXCLUDED.tech_stack,
  year = EXCLUDED.year,
  status = EXCLUDED.status,
  featured = EXCLUDED.featured,
  project_type = EXCLUDED.project_type,
  platforms = EXCLUDED.platforms,
  disciplines = EXCLUDED.disciplines,
  ownership = EXCLUDED.ownership,
  team_size = EXCLUDED.team_size,
  duration = EXCLUDED.duration,
  impact_summary = EXCLUDED.impact_summary,
  technical_highlights = EXCLUDED.technical_highlights,
  architecture_notes = EXCLUDED.architecture_notes,
  tradeoffs = EXCLUDED.tradeoffs,
  metrics = EXCLUDED.metrics,
  demo_url = EXCLUDED.demo_url,
  demo_video_url = EXCLUDED.demo_video_url,
  github_url = EXCLUDED.github_url,
  case_study_visibility = EXCLUDED.case_study_visibility,
  sort_order = EXCLUDED.sort_order,
  sort_date = EXCLUDED.sort_date,
  updated_at = NOW();

-- =====================================================================================
-- 2) Atomic — Interactive 3D Periodic Table & Chemistry Lab
-- =====================================================================================
INSERT INTO projects (
  id,
  title,
  slug,
  summary,
  description,
  problem,
  solution,
  result,
  role,
  tech_stack,
  year,
  status,
  featured,
  project_type,
  platforms,
  disciplines,
  ownership,
  team_size,
  duration,
  impact_summary,
  technical_highlights,
  architecture_notes,
  tradeoffs,
  metrics,
  demo_url,
  demo_video_url,
  github_url,
  case_study_visibility,
  sort_order,
  sort_date,
  inserted_at,
  updated_at
) VALUES (
  'a1111111-2222-4333-8444-555500000002',
  'Atomic — Interactive 3D Periodic Table & Chemistry Lab',
  'atomic-interactive-3d-periodic-table',
  $$Web app edukasi 3D tabel periodik 118 unsur dengan Bohr model, molecule builder, dan konten sinematik; terintegrasi ke shared backend SAINS untuk auth dan subscription.$$,
  $$Atomic adalah web app edukasi yang membangun ulang tabel periodik, struktur atom, dan fenomena kimia dalam format interaktif dan sinematik. Pengguna bisa memutar model atom Bohr 3D per elemen, menyusun molekul di Kimia Lab, dan membaca narasi sejarah atom serta asal usul kosmik tiap unsur. App di-deploy ke app.sains-atomic.web.id dan di-hit oleh landing page SEO di sains-atomic.web.id, serta memakai subscription gate yang di-back oleh SAINS API.$$,
  $$Pelajar SMA dan mahasiswa Indonesia sering kesulitan membayangkan struktur atom, tabel periodik, dan fenomena kimia karena materi dominan hadir sebagai teks 2D di buku. Aplikasi pendidikan kimia yang ada juga umumnya hanya tabel statis tanpa visual 3D, tanpa story, dan tanpa experimen interaktif, sehingga murid kehilangan minat sebelum memahami inti konsepnya.$$,
  $$Membangun SPA TypeScript murni dengan Vite dan Three.js, tanpa framework UI, agar bundle tetap ringan dan scene 3D tidak bersaing dengan Virtual DOM. Atom Bohr divisualisasikan per elemen dengan orbit elektron animasi, drag untuk rotate, dan scroll untuk zoom; Kimia Lab memakai rule-based chemistry deduction engine untuk memvalidasi kombinasi atom menjadi molekul yang masuk akal.

Auth, pricing, dan pembayaran di-delegate ke SAINS API lewat fetch + JWT, dengan mode demo khusus (#/molecule-demo) yang bisa di-embed sebagai iframe di landing page tanpa login. Konten sinematik (22 slide sejarah atom, 27 fenomena, 118 elemen) ditulis sebagai data terstruktur supaya komponen bisa render konsisten dan bilingual (ID/EN) langsung dari toggle.$$,
  ARRAY[
    'Live di https://app.sains-atomic.web.id dengan 118 elemen lengkap dan 32 molekul di Molecule Builder.',
    'Landing page SEO di https://sains-atomic.web.id dan varian pendidikan keluarga di /pendidikan/.',
    'SEO pages dedicated: /tabel-periodik/ dan /cara-belajar-kimia/ terhubung ke app produk.',
    'Demo Mode ter-embed di landing page sebagai iframe (#/molecule-demo) sebagai growth hook ke subscription.',
    'Konten bilingual ID/EN dan dark/light mode persist di localStorage.'
  ],
  'Solo frontend engineer / product + content designer',
  ARRAY[
    'TypeScript 5.x',
    'Vite 7.x',
    'Three.js 0.183',
    'Vanilla CSS',
    'Hash-based SPA router (custom)',
    'i18n ID/EN (custom)',
    'localStorage',
    'WebGL',
    'SAINS API (JWT fetch)'
  ],
  '2026',
  'published',
  TRUE,
  'personal_project',
  ARRAY['web'],
  ARRAY['frontend_developer'],
  'Solo builder untuk arsitektur SPA, integrasi Three.js, kurasi konten 118 elemen + story, dan integrasi ke SAINS API.',
  'Solo project',
  '2026',
  $$Menunjukkan kemampuan merancang SPA interaktif berat 3D tanpa framework UI, mengatur lifecycle scene agar bebas memory leak saat route berubah, dan memadukan konten edukasi skala besar dengan subscription gate yang berjalan di backend terpisah.$$,
  ARRAY[
    '3D atom visualizer Bohr model dengan orbit elektron animasi (Three.js), drag-to-rotate, scroll-to-zoom, dan dukungan mouse + touch.',
    'Molecule Builder dengan 32 molekul (gas, organik, anorganik, asam, basa, oksida, garam, material), 18 atom di palette, dan Chemistry Deduction Engine rule-based.',
    'Kimia Lab Challenge Mode: 15 tantangan (5 easy / 5 medium / 5 hard) dengan hint system + feedback interaktif.',
    'Demo Mode terisolasi (palette H/O/C saja, 15 atom terkunci dengan overlay upgrade) untuk iframe embed di landing page.',
    'Komponen dengan pola render HTML string → bind event → mount Three.js → return cleanup, agar scene di-dispose rapi saat route berubah.',
    'Bilingual ID/EN runtime toggle dan dark/light mode persist di localStorage.'
  ],
  $$Satu entry main.ts men-boot theme, auth (/api/auth/me), dan hash-based SPA router. Setiap komponen mengikuti pola seragam: render HTML string, query DOM, bind event, opsional mount Three.js, dan mengembalikan cleanup function. Integrasi ke backend murni via fetch ke SAINS API di https://sains-atomic.web.id/api, dengan product=atomic di query param.

Mode demo (#/molecule-demo) sengaja dipisah sebagai route publik tanpa auth dengan palette terbatas, sehingga bisa di-embed sebagai iframe di landing page tanpa bocor ke fitur berbayar.$$,
  $$Sengaja tanpa framework UI (React/Vue/Svelte) agar bundle tetap kecil dan scene 3D tidak berkompetisi dengan Virtual DOM. Konsekuensinya state dikelola manual di modul dan DOM, dan tidak ada unit test formal di fase MVP, hanya manual testing. Semua komponen masih di-load upfront (belum lazy) karena volume sekarang masih masuk akal, tetapi diakui sebagai ruang optimasi selanjutnya. Paywall gate di frontend sengaja ditinggalkan di tahap akhir karena semua endpoint pendukung (/api/access-check, /api/checkout, webhook Midtrans) sudah siap di backend.$$,
  ARRAY[
    '118 elemen lengkap dengan 11 kategori color-coded (Logam Alkali, Halogen, Gas Mulia, dll).',
    '32 molekul, 18 atom palette, 15 challenge mode di Kimia Lab.',
    '22 slide sinematik sejarah atom dan 27 fenomena dalam 6 kategori.',
    'Public proof: live di https://app.sains-atomic.web.id dengan SEO pages ter-index.'
  ],
  'https://app.sains-atomic.web.id',
  NULL,
  'https://github.com/nunutech40/atomic',
  'public',
  1,
  DATE '2026-03-05',
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  problem = EXCLUDED.problem,
  solution = EXCLUDED.solution,
  result = EXCLUDED.result,
  role = EXCLUDED.role,
  tech_stack = EXCLUDED.tech_stack,
  year = EXCLUDED.year,
  status = EXCLUDED.status,
  featured = EXCLUDED.featured,
  project_type = EXCLUDED.project_type,
  platforms = EXCLUDED.platforms,
  disciplines = EXCLUDED.disciplines,
  ownership = EXCLUDED.ownership,
  team_size = EXCLUDED.team_size,
  duration = EXCLUDED.duration,
  impact_summary = EXCLUDED.impact_summary,
  technical_highlights = EXCLUDED.technical_highlights,
  architecture_notes = EXCLUDED.architecture_notes,
  tradeoffs = EXCLUDED.tradeoffs,
  metrics = EXCLUDED.metrics,
  demo_url = EXCLUDED.demo_url,
  demo_video_url = EXCLUDED.demo_video_url,
  github_url = EXCLUDED.github_url,
  case_study_visibility = EXCLUDED.case_study_visibility,
  sort_order = EXCLUDED.sort_order,
  sort_date = EXCLUDED.sort_date,
  updated_at = NOW();

-- =====================================================================================
-- 3) Klinik — Invoice & Kwitansi Generator untuk Dokter Praktek Mandiri
-- =====================================================================================
INSERT INTO projects (
  id,
  title,
  slug,
  summary,
  description,
  problem,
  solution,
  result,
  role,
  tech_stack,
  year,
  status,
  featured,
  project_type,
  platforms,
  disciplines,
  ownership,
  team_size,
  duration,
  impact_summary,
  technical_highlights,
  architecture_notes,
  tradeoffs,
  metrics,
  demo_url,
  demo_video_url,
  github_url,
  case_study_visibility,
  sort_order,
  sort_date,
  inserted_at,
  updated_at
) VALUES (
  'a1111111-2222-4333-8444-555500000003',
  'Klinik — Invoice & Kwitansi Generator untuk Dokter Praktek Mandiri',
  'klinik-invoice-dokter-web-app',
  $$Web app niche untuk dokter praktek mandiri membuat invoice dan kwitansi pasien print-ready, dengan auth dan subscription yang reuse backend SAINS tanpa perubahan server.$$,
  $$Klinik adalah web app yang mengganti kebiasaan bikin kwitansi manual atau di Excel dengan satu workflow isi form, live preview, lalu print. Profil dokter dan riwayat invoice disimpan di localStorage, sementara auth dan pricing di-delegate ke SAINS API. Pendekatan ini dipilih untuk validasi demand secara cepat sebelum invest di backend invoice.$$,
  $$Dokter praktek mandiri tidak punya tool kwitansi yang rapi dan konsisten; copy-paste di Word atau Excel membuat header harus diisi ulang tiap transaksi, arsip mudah hilang, dan rekap pendapatan bulanan harus dihitung manual. Solusi berat seperti rekam medis penuh terasa over-engineered untuk praktek mandiri yang volumenya rendah dan sensitivitasnya tinggi.$$,
  $$Membangun SPA TypeScript + Vite dengan pola fork dari arsitektur Atomic, tetapi di-rewrite untuk fokus pada CRUD invoice, live preview print-ready, dan auto-fill profil dokter. Auth, pricing, checkout Midtrans, dan access-check di-delegate sepenuhnya ke SAINS API dengan query param product=klinik, sehingga zero backend change saat launching produk baru ini.

Invoice dan profil dokter sengaja disimpan di localStorage dengan namespace unik (klinik_access_token, klinik_doctor_profile, klinik_invoices) supaya bisa hidup berdampingan dengan produk SAINS lain di browser yang sama. Print memakai CSS @media print dan window.print() agar output rapi tanpa library PDF berat.$$,
  ARRAY[
    'Live di https://app.invoiceklinik.web.id dan landing SEO di https://invoiceklinik.web.id.',
    'Reuse 100 persen backend SAINS: /api/auth/*, /api/plans?product=klinik, /api/checkout, /api/access-check?product=klinik.',
    'Session terisolasi dari produk lain lewat key localStorage khusus Klinik.',
    'SEO pages dedicated: /invoice-dokter/ dan /kwitansi-pasien/ untuk long-tail keyword dengan kompetisi rendah.',
    'CORS produksi dan konfigurasi Nginx siap untuk subdomain app.invoiceklinik.web.id.'
  ],
  'Solo frontend engineer / product',
  ARRAY[
    'TypeScript',
    'Vite',
    'Vanilla CSS',
    'Hash-based SPA router (custom)',
    'localStorage CRUD',
    'SAINS API (JWT fetch)',
    'Midtrans Snap (via SAINS API)',
    'jsPDF',
    'Cloudflare',
    'Nginx',
    'IDCloudHost VPS'
  ],
  '2026',
  'published',
  TRUE,
  'personal_project',
  ARRAY['web'],
  ARRAY['frontend_developer'],
  'Solo builder untuk riset pasar, fork arsitektur dari Atomic, rewrite UI invoice + preview print, setup landing SEO, dan integrasi ke SAINS API.',
  'Solo project',
  '2026',
  $$Menunjukkan disiplin mengirim produk niche dengan cepat dengan cara reuse backend yang sudah ada, membuat session terisolasi per produk, dan memilih storage sesuai level validasi pasar. Fokus ke workflow harian user (form → preview → print) daripada ke fitur besar yang belum terbukti dibayar.$$,
  ARRAY[
    'Form invoice multi-row layanan dengan live preview print-ready yang langsung memicu window.print() tanpa dependency PDF berat.',
    'Auto-fill profil dokter dari klinik_doctor_profile di localStorage, sehingga header kwitansi tidak perlu diisi ulang tiap transaksi.',
    'Zero backend change: semua auth dan payment di-route lewat SAINS API dengan query param product=klinik.',
    'Isolated session keys (klinik_access_token, klinik_user, klinik_invoices, klinik_doctor_profile) agar Klinik hidup berdampingan dengan Atomic, Surat, dan KontrakPro di browser yang sama.',
    'Admin bypass: akun admin SAINS otomatis lolos subscription gate saat dev untuk mempercepat iterasi.',
    'Landing SEO terpisah di invoiceklinik.web.id dengan long-tail keyword dokter praktek mandiri.'
  ],
  $$Boot flow main.ts → initAuth() → checkAccess(product=klinik) → Dashboard atau PricingPage. Integrasi backend murni fetch ke SAINS API; tidak ada service atau skema khusus Klinik di sisi server. Karena target user adalah profesional dewasa yang butuh akun permanen, semua halaman fitur adalah paywall penuh, tidak ada mode guest seperti di Atomic.$$,
  $$Invoice sengaja disimpan di localStorage alih-alih backend untuk mempercepat validasi pasar; konsekuensinya data hilang kalau browser di-clear dan tidak sinkron lintas device, dan ini diterima terbuka di tahap MVP. Tidak ada mode guest supaya flow tetap sederhana untuk target user profesional. Pricing di landing page di-hardcode di HTML (bukan fetch dari API) untuk SEO yang ringan dan render tanpa blocking, konsekuensinya setiap update harga butuh edit manual.$$,
  ARRAY[
    '2 SEO landing pages target keyword high-intent (invoice dokter, kwitansi pasien) dengan kompetisi mendekati nol menurut riset.',
    'Pricing plan global: Rp 99.000/bulan dan Rp 699.000/tahun.',
    'Public proof: live di https://app.invoiceklinik.web.id dengan landing SEO ter-index.'
  ],
  'https://app.invoiceklinik.web.id',
  NULL,
  'https://github.com/nunutech40/invoice-generator-klinik',
  'public',
  1,
  DATE '2026-03-10',
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  problem = EXCLUDED.problem,
  solution = EXCLUDED.solution,
  result = EXCLUDED.result,
  role = EXCLUDED.role,
  tech_stack = EXCLUDED.tech_stack,
  year = EXCLUDED.year,
  status = EXCLUDED.status,
  featured = EXCLUDED.featured,
  project_type = EXCLUDED.project_type,
  platforms = EXCLUDED.platforms,
  disciplines = EXCLUDED.disciplines,
  ownership = EXCLUDED.ownership,
  team_size = EXCLUDED.team_size,
  duration = EXCLUDED.duration,
  impact_summary = EXCLUDED.impact_summary,
  technical_highlights = EXCLUDED.technical_highlights,
  architecture_notes = EXCLUDED.architecture_notes,
  tradeoffs = EXCLUDED.tradeoffs,
  metrics = EXCLUDED.metrics,
  demo_url = EXCLUDED.demo_url,
  demo_video_url = EXCLUDED.demo_video_url,
  github_url = EXCLUDED.github_url,
  case_study_visibility = EXCLUDED.case_study_visibility,
  sort_order = EXCLUDED.sort_order,
  sort_date = EXCLUDED.sort_date,
  updated_at = NOW();

-- =====================================================================================
-- 4) KontrakPro — Proposal / Kontrak / Invoice untuk Freelancer & Agensi
-- =====================================================================================
INSERT INTO projects (
  id,
  title,
  slug,
  summary,
  description,
  problem,
  solution,
  result,
  role,
  tech_stack,
  year,
  status,
  featured,
  project_type,
  platforms,
  disciplines,
  ownership,
  team_size,
  duration,
  impact_summary,
  technical_highlights,
  architecture_notes,
  tradeoffs,
  metrics,
  demo_url,
  demo_video_url,
  github_url,
  case_study_visibility,
  sort_order,
  sort_date,
  inserted_at,
  updated_at
) VALUES (
  'a1111111-2222-4333-8444-555500000004',
  'KontrakPro — Proposal, Kontrak, Invoice untuk Freelancer & Agensi',
  'kontrakpro-proposal-kontrak-invoice-freelancer',
  $$Web app unified untuk freelancer dan agensi kecil Indonesia yang menyatukan proposal, kontrak, dan invoice dalam satu flow terkait dengan Client Portal publik lewat shareable link.$$,
  $$KontrakPro adalah web app yang menyatukan tiga dokumen bisnis (proposal, kontrak, invoice) yang biasanya tersebar di Canva, Word, dan Excel menjadi satu flow di satu tab project. Auth dan pembayaran di-delegate ke SAINS API, semua data dokumen disimpan di localStorage, dan Client Portal publik memakai shareable link supaya client bisa melihat dokumen tanpa login. Tagline internal: "Dari proposal sampai dibayar, 1 platform."$$,
  $$Freelancer dan agensi kecil biasanya melompat antar tool untuk membuat proposal, kontrak, dan invoice: proposal di Canva, kontrak di Word, invoice di Excel. Hasilnya branding tidak konsisten, client lama approve, nomor dokumen tidak terstruktur, dan banyak pembayaran terlewat karena tidak ada tracking termin yang tersambung ke invoice.$$,
  $$Membangun SPA TypeScript + Vite dengan satu halaman ProjectDetail yang punya tiga tab (Proposal, Kontrak, Invoice). Generator kontrak dan invoice dirender inline di tab, bukan pindah halaman, agar context tidak terputus. Data disimpan di localStorage dengan model strongly-typed (Proposal, Kontrak, Invoice, PricingItem, PaymentTermin) dan cascade delete antar entitas.

Client Portal publik dibangun di atas shareable link berformat /share/:type/:token, sehingga client bisa membuka proposal atau invoice tanpa perlu akun. Auth dan subscription delegate ke SAINS API dengan product=kontrak. Design system memakai Plus Jakarta Sans dengan palette indigo/violet untuk UI, dan Inter untuk dokumen preview agar terasa dokumen resmi.$$,
  ARRAY[
    'Live di https://app.kontrakpro.web.id dan landing SEO di https://kontrakpro.web.id.',
    'GA4 (G-P8CL3XSQJB) dan Google Search Console aktif untuk tracking funnel dan indexing.',
    '5 phase pengembangan (Setup, Proposal Builder, Kontrak + Invoice + Client Portal, Landing + Deploy + SEO, UX Overhaul v2) tuntas per 15 Maret 2026.',
    '5 template proposal siap pakai (design, development, photography, marketing, general).',
    'VPS health stabil setelah tambah 2GB swap dan membersihkan 604MB log.'
  ],
  'Solo full-stack engineer / product designer',
  ARRAY[
    'TypeScript',
    'Vite',
    'Vanilla CSS',
    'Plus Jakarta Sans',
    'Inter',
    'Hash-based SPA router (custom)',
    'localStorage',
    'SAINS API (JWT fetch)',
    'Midtrans Snap (via SAINS API)',
    'Google Analytics 4',
    'Google Search Console',
    'Cloudflare',
    'Nginx',
    'IDCloudHost VPS'
  ],
  '2026',
  'published',
  TRUE,
  'personal_project',
  ARRAY['web'],
  ARRAY['frontend_developer', 'fullstack_developer'],
  'Solo builder untuk riset produk premium, desain UX 3 tab unified, 5 template proposal, landing SEO, deploy VPS, dan integrasi ke SAINS API.',
  'Solo project',
  '2026',
  $$Menunjukkan kemampuan merancang UX workflow dokumen bisnis end-to-end yang konsisten, mengambil keputusan storage dan client-sharing yang pragmatis, dan menjaga konsistensi branding lewat design system yang punya alasan jelas antara UI dan dokumen.$$,
  ARRAY[
    'Unified 3-tab ProjectDetail: kontrak generator dan invoice generator dirender inline di tab, menghilangkan flow multi-page.',
    'Dual discount system: per-item discount plus global discount, masing-masing support persen atau rupiah, konsisten dari proposal ke kontrak dan invoice.',
    'Payment Termin terstruktur (DP, Pelunasan, atau custom) dengan auto-calculate amount per termin dan termin-based invoicing.',
    'Cascade delete: hapus proposal otomatis menghapus kontrak dan invoice turunan agar tidak ada orphan record.',
    'PrintAllView: print proposal, kontrak, dan invoice sekaligus dalam satu view untuk handover ke client.',
    'Demo Mode dengan GA4 funnel tracking dan paywall untuk eksperimen konversi.',
    'Design system spesifik: Plus Jakarta Sans untuk UI, Inter untuk dokumen preview agar terasa dokumen resmi.'
  ],
  $$Routing hash-based dengan semua rute /proposal/:id, /kontrak/:id, /invoice/:id konvergen ke komponen ProjectDetail sehingga state editing terpusat di satu tempat. Data model strongly-typed di TypeScript: Proposal, Kontrak, Invoice, PricingItem, PaymentTermin, dengan relasi cascade delete yang eksplisit di layer storage. Client Portal publik memakai shareable link /share/:type/:token agar client bisa melihat dokumen tanpa login, alih-alih bikin sistem akun tamu di backend.$$,
  $$Client Portal MVP memakai shareable link plus output PDF/WhatsApp alih-alih backend per-user untuk menghindari scope creep dan ship cepat. Template proposal punya default section, tetapi user bisa menyesuaikan, sebagai mitigasi risiko template tidak cocok untuk semua industri. Kontrak memiliki disclaimer eksplisit bahwa template hanya acuan umum dan user perlu konsultasi ahli hukum, karena akurasi legal bukan tanggung jawab produk. Pricing plan masih hardcoded di PricingPage (belum dipindah ke DB) dan dicatat sebagai pending task.$$,
  ARRAY[
    'Pricing positioning premium Rp 199.000 sampai Rp 399.000 per bulan untuk segmen freelancer dengan income Rp 10 juta sampai Rp 80 juta per bulan.',
    '4 series nomor dokumen ter-generate otomatis: PROP-YYYY-####, KON-YYYY-####, INV-YYYY-####.',
    'Public proof: GA4 dan Google Search Console aktif, domain dan app live, repo publik.'
  ],
  'https://app.kontrakpro.web.id',
  NULL,
  'https://github.com/nunutech40/kontrakpro',
  'public',
  1,
  DATE '2026-03-15',
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  problem = EXCLUDED.problem,
  solution = EXCLUDED.solution,
  result = EXCLUDED.result,
  role = EXCLUDED.role,
  tech_stack = EXCLUDED.tech_stack,
  year = EXCLUDED.year,
  status = EXCLUDED.status,
  featured = EXCLUDED.featured,
  project_type = EXCLUDED.project_type,
  platforms = EXCLUDED.platforms,
  disciplines = EXCLUDED.disciplines,
  ownership = EXCLUDED.ownership,
  team_size = EXCLUDED.team_size,
  duration = EXCLUDED.duration,
  impact_summary = EXCLUDED.impact_summary,
  technical_highlights = EXCLUDED.technical_highlights,
  architecture_notes = EXCLUDED.architecture_notes,
  tradeoffs = EXCLUDED.tradeoffs,
  metrics = EXCLUDED.metrics,
  demo_url = EXCLUDED.demo_url,
  demo_video_url = EXCLUDED.demo_video_url,
  github_url = EXCLUDED.github_url,
  case_study_visibility = EXCLUDED.case_study_visibility,
  sort_order = EXCLUDED.sort_order,
  sort_date = EXCLUDED.sort_date,
  updated_at = NOW();

-- =====================================================================================
-- 5) Surat — Generator Surat & Dokumen Profesional Indonesia (Template Engine)
-- =====================================================================================
INSERT INTO projects (
  id,
  title,
  slug,
  summary,
  description,
  problem,
  solution,
  result,
  role,
  tech_stack,
  year,
  status,
  featured,
  project_type,
  platforms,
  disciplines,
  ownership,
  team_size,
  duration,
  impact_summary,
  technical_highlights,
  architecture_notes,
  tradeoffs,
  metrics,
  demo_url,
  demo_video_url,
  github_url,
  case_study_visibility,
  sort_order,
  sort_date,
  inserted_at,
  updated_at
) VALUES (
  'a1111111-2222-4333-8444-555500000005',
  'Surat — Generator Surat & Dokumen Profesional Indonesia',
  'surat-generator-dokumen-resmi-indonesia',
  $$Web app generator surat resmi Indonesia dengan template engine JSON yang membuat penambahan template baru selesai dalam hitungan menit, dengan model freemium yang di-back oleh SAINS API.$$,
  $$Surat adalah web app yang mengganti kebiasaan copy-paste contoh surat dari Google lalu edit manual di Word dengan satu workflow pilih template, isi form, lalu print. Setiap template adalah satu file TypeScript dengan fields dan renderLayout, sehingga penambahan template surat baru tidak butuh edit form engine, cukup satu file baru di registry. Model freemium (3 surat per bulan gratis) dipilih untuk memperluas funnel akuisisi sebelum user beralih ke paid plan.$$,
  $$Lebih dari 800 ribu pencarian per bulan untuk kata kunci "contoh surat" di Google diarahkan ke blog statis yang meminta user copy-paste, edit manual di Word, lalu print dengan hasil tidak konsisten. Di Play Store 6 dari 7 aplikasi serupa hanya fokus pada satu kategori surat lamaran kerja, tidak ada generator general-purpose untuk surat resmi Indonesia yang punya template engine scalable.$$,
  $$Membangun SPA TypeScript + Vite dengan template engine berbasis JSON config: tiap template adalah file src/templates/surat-[nama].ts yang export TemplateConfig berisi fields[] dan renderLayout(data, letterhead). Form dinamis dihasilkan otomatis dari fields[] dan preview live memakai renderLayout, output lewat window.print(). Menambah template baru kira-kira selesai dalam 30 menit tanpa sentuh form engine.

Auth dan subscription delegate ke SAINS API dengan product=surat, tapi model gating berbeda dari Klinik: freemium 3 surat per bulan gratis, dengan counter tersimpan di localStorage. Light theme dipilih agar WYSIWYG dengan hasil cetak di kertas putih, print memakai @media print CSS tanpa dependency PDF berat.$$,
  ARRAY[
    'Live di https://app.dokumensurat.web.id dan landing SEO di https://dokumensurat.web.id.',
    'SEO pages dedicated: /surat-lamaran-kerja/ dan /surat-keterangan/ untuk keyword high-intent.',
    '5+ template surat Indonesia aktif dan ekspandable lewat registry.',
    'Template engine scalable: tambah template baru kurang lebih 30 menit tanpa sentuh form engine.',
    'PRD, TRD, ARCHITECTURE, TEMPLATES, RESEARCH semua lengkap sebelum build sebagai evidence disiplin spec-first.'
  ],
  'Solo frontend engineer / product',
  ARRAY[
    'TypeScript',
    'Vite',
    'Vanilla CSS',
    'Hash-based SPA router (custom)',
    'localStorage',
    'JSON-based template engine (custom)',
    'SAINS API (JWT fetch)',
    'Midtrans Snap (via SAINS API)',
    'Cloudflare',
    'Nginx',
    'IDCloudHost VPS'
  ],
  '2026',
  'published',
  TRUE,
  'personal_project',
  ARRAY['web'],
  ARRAY['frontend_developer'],
  'Solo builder untuk riset keyword demand, desain template engine JSON, 5+ template Indonesia, fork arsitektur dari Klinik dengan delta eksplisit, landing SEO, deploy, dan integrasi ke SAINS API.',
  'Solo project',
  '2026',
  $$Menunjukkan kemampuan merancang template engine scalable untuk produk konten-heavy, mengambil keputusan model gating (freemium vs paywall penuh) berbasis profil user, dan mempertahankan konsistensi arsitektur antar produk SAINS lewat fork discipline yang eksplisit.$$,
  ARRAY[
    'Template Engine: 1 file TypeScript per template (fields[] + renderLayout()), registry sentral, form dan preview otomatis dihasilkan dari config.',
    '5+ template surat Indonesia: Surat Lamaran Kerja, Keterangan Domisili, Resign, Kuasa, Pengantar RT, dengan field type beragam (text, date, textarea, dll).',
    'LetterheadEditor: kop surat reusable yang di-attach ke template yang membutuhkannya lewat flag needsLetterhead.',
    'Print-optimized CSS dengan @media print sehingga preview match hasil print di kertas putih.',
    'Search dan filter by category di dashboard template grid.',
    'Fork discipline dicatat eksplisit: daftar file copy-as-is dari Klinik versus file rewrite khusus Surat, mempermudah maintain konsistensi arsitektur antar produk.'
  ],
  $$Boot flow konsisten dengan produk SAINS lain: main.ts → initAuth() → checkAccess(product=surat) → Dashboard atau PricingPage. Data model berbeda dari Klinik: surat_letters dan surat_letterhead di localStorage. Template engine ada di jantung aplikasi: menambah template baru berarti satu file src/templates/surat-[nama].ts plus registry update, dan form serta preview menyesuaikan otomatis.$$,
  $$Memilih freemium (3 surat gratis per bulan) alih-alih full paywall karena target market lebih luas dan butuh funnel akuisisi; risk user clear storage untuk reset counter diterima sebagai trade-off MVP yang bisa diperketat kemudian. Data di localStorage mengikuti pola Klinik untuk mempercepat validasi demand sebelum invest di cloud sync. Light theme dipilih alih-alih dark agar preview WYSIWYG dengan hasil cetak di kertas putih. Template-based architecture butuh disiplin type (FieldDefinition, TemplateConfig), trade-off yang membayar diri sendiri ketika jumlah template tumbuh.$$,
  ARRAY[
    'Target keyword demand: 800 ribu+ pencarian per bulan untuk kata kunci "contoh surat" di Google (riset internal).',
    '5+ template aktif (Lamaran, Keterangan Domisili, Resign, Kuasa, Pengantar RT), ekspandable via registry.',
    'Public proof: live di https://app.dokumensurat.web.id dengan 2 SEO page dedicated ter-index.'
  ],
  'https://app.dokumensurat.web.id',
  NULL,
  'https://github.com/nunutech40/template-surat',
  'public',
  1,
  DATE '2026-03-10',
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  description = EXCLUDED.description,
  problem = EXCLUDED.problem,
  solution = EXCLUDED.solution,
  result = EXCLUDED.result,
  role = EXCLUDED.role,
  tech_stack = EXCLUDED.tech_stack,
  year = EXCLUDED.year,
  status = EXCLUDED.status,
  featured = EXCLUDED.featured,
  project_type = EXCLUDED.project_type,
  platforms = EXCLUDED.platforms,
  disciplines = EXCLUDED.disciplines,
  ownership = EXCLUDED.ownership,
  team_size = EXCLUDED.team_size,
  duration = EXCLUDED.duration,
  impact_summary = EXCLUDED.impact_summary,
  technical_highlights = EXCLUDED.technical_highlights,
  architecture_notes = EXCLUDED.architecture_notes,
  tradeoffs = EXCLUDED.tradeoffs,
  metrics = EXCLUDED.metrics,
  demo_url = EXCLUDED.demo_url,
  demo_video_url = EXCLUDED.demo_video_url,
  github_url = EXCLUDED.github_url,
  case_study_visibility = EXCLUDED.case_study_visibility,
  sort_order = EXCLUDED.sort_order,
  sort_date = EXCLUDED.sort_date,
  updated_at = NOW();
